### ISSUE TITLE
`customJdk` seems to refer to missing output

### ISSUE THREAD

**Issue by neshtea** [jlesquembre/clj-nix#16] opened 2022-06-02 08:20 UTC
# Description

I am trying to build a `customJdk` from an existing `mkCljBin`, as described in the tutorial.  This then fails with

```
$ nix build .#project-jdk
error: builder for '/nix/store/<hash>-<project>-standalone.drv' failed with exit code 2;
       last 9 log lines:
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > installing
       > Error: invalid argument: Path does not exist: /nix/store/<hash>-<project>-standalone-0.1.0-lib/<project>-standalone-0.1.0.jar --compress 2 --output /nix/store/<hash>-<project>-standalone-jdk
       > Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
       > Use --help for a list of possible options
       For full logs, run 'nix log /nix/store/<hash>-<project>standalone.drv'.
```

Take note of the `-lib/` part of the error message.  This output seems to be missing from the "normal" `mkCljBin` output:

```
$ nix build .#project
...
$ tree result
result
├── bin
│   └── <project>-standalone
└── nix-support
    └── propagated-build-inputs
```

I think older versions of `clj-nix` generated the `lib` output.  Am I missing something or is this a bug?

**Comment by jlesquembre** [comment] 2022-06-02 09:14
Thanks for the report, I was not able to reproduce it yet. In the [demo project](https://github.com/jlesquembre/clj-demo-project) works as expected:

```
nix build github:jlesquembre/clj-demo-project#jdk-tuto
```

My guess is that you are generating the uberjar passing a custom command to `mkCljBin.buildCommand` and something is wrong there. (Maybe the jar doesn't end in the `target` directory?)

To debug it, you could try to run `nix build .#project.lib`, the jar should be in the `result-lib` directory.

You could also take a look to the `result/bin/<project>-standalone` generated by the `nix build .#project` command. It's a bash script, and it should contain the path to your application jar

**Comment by neshtea** [comment] 2022-06-02 09:38
Thanks for you swift response.

> My guess is that you are generating the uberjar passing a custom command to mkCljBin.buildCommand and something is wrong there. (Maybe the jar doesn't end in the target directory?)

Possibly, but the resulting uberjar is produced and correctly placed under `target/<project>-standalone.jar`.

> To debug it, you could try to run nix build .#project.lib, the jar should be in the result-lib directory.

I did that and it produces the correct output.

> You could also take a look to the result/bin/<project>-standalone generated by the nix build .#project command. It's a bash script, and it should contain the path to your application jar

It does, and it has the same hash as the not found lib in the `customJdk` output.

I will keep investigating and will report back when I found the cause.

**Comment by jlesquembre** [comment] 2022-06-02 09:44
oh, wait, I think I found a bug

**Comment by jlesquembre** [comment] 2022-06-02 10:25
Could you test again with latest change from `main` branch?

**Comment by neshtea** [comment] 2022-06-02 12:48
> @neshtea Could you test again with latest change from `main` branch?

Perfect, it gets along way further (and stops at another error because of multi-stage builds, but that is unrelated to this). Thanks for fixing!

**Comment by jlesquembre** [comment] 2022-06-02 13:25
@neshtea nice! Thanks for testing clj-nix and reporting issues. Since seems fixed, I'm closing this one.

Not sure what error are you getting with multi-stage builds, but open a new issue if needed, I'll try to help :)

**Closed by jlesquembre** 2022-06-02 13:25 UTC
